# Generated by Django 5.1.3 on 2024-12-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_id", models.CharField(max_length=100, unique=True)),
                ("signing_key", models.CharField(max_length=100)),
            ],
        ),
    ]
