repos:
  - repo: local
    hooks:
      - id: migrations-check
        name: migrations-check
        entry: poetry run python manage.py makemigrations --check
        language: system
        types: []
        pass_filenames: false

      - id: format
        name: format
        entry: poetry run ruff format .
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: lint
        entry: poetry run ruff check --fix .
        language: system
        types: [python]
        pass_filenames: false

      - id: export-requirements
        name: export
        entry: poetry export -o requirements.txt --without-hashes
        language: system
        types: []
        pass_filenames: false