# Generated by Django 5.1.3 on 2024-12-13 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gameplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.IntegerField()),
                ("image_url", models.URLField()),
                ("blurhash", models.CharField()),
                ("color", models.CharField()),
                ("score", models.IntegerField(null=True)),
                ("title", models.CharField()),
                ("artist", models.CharField()),
                ("supply", models.IntegerField()),
                ("season", models.IntegerField()),
                ("title_options", models.JSONField()),
                ("artist_options", models.JSONField()),
                ("supply_options", models.JSONField()),
                ("season_options", models.JSONField()),
                ("title_answer", models.CharField(blank=True, null=True)),
                ("artist_answer", models.CharField(blank=True, null=True)),
                ("supply_answer", models.IntegerField(null=True)),
                ("season_answer", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gameplay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="know_your_memes.gameplay",
                    ),
                ),
            ],
        ),
    ]
