# Generated by Django 5.1.3 on 2024-12-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("know_your_memes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="artist",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="artist_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="blurhash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="color",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="question",
            name="image_url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="title_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
