# Generated by Django 5.1.3 on 2024-12-12 07:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                (
                    "eth_address",
                    models.CharField(
                        max_length=42,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_eth_address",
                                message="Enter a valid Ethereum address. It should start with 0x followed by 40 hexadecimal characters.",
                                regex="^0x[a-fA-F0-9]{40}$",
                            )
                        ],
                    ),
                ),
                ("url", models.URLField()),
                (
                    "nft_address",
                    models.CharField(
                        max_length=42,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_eth_address",
                                message="Enter a valid Ethereum address. It should start with 0x followed by 40 hexadecimal characters.",
                                regex="^0x[a-fA-F0-9]{40}$",
                            )
                        ],
                    ),
                ),
                (
                    "signing_key",
                    models.CharField(
                        max_length=66,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_bytes32_hex",
                                message="Enter a valid bytes32 hex value. It should start with 0x followed by 64 lowercase hexadecimal characters.",
                                regex="^0x[a-f0-9]{64}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerHighScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.BigIntegerField(default=0)),
                ("token_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "game"), name="unique_user_game"
                    )
                ],
            },
        ),
    ]
