# Generated by Django 5.1.4 on 2025-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="url",
            field=models.TextField(),
        ),
    ]
